# Sample workflow for building and deploying a Hugo site to CloudFlare Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to CloudFlare Pages
permissions:
  contents: read
  deployments: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build-deploy:
    runs-on: ubuntu-24.04
    environment: 
      name: production
      url: ${{ steps.publish.outputs.deployment-url }}
    name: Deploy to CloudFlare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup target Node.js to enable Corepack
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          
      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install

      - name: Build with Hugo
        run: yarn build

      - name: Publish
        id: publish
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
